name: Pull Request CI

on:
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Frontend dependencies
        run: cd frontend && npm ci

      - name: Install Backend dependencies
        run: cd backend && npm ci

      - name: Lint Frontend
        run: cd frontend && npm run lint

      - name: Type check Frontend
        run: cd frontend && npm run type-check || true

      - name: Test Frontend
        run: cd frontend && npm run test || true

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Build Backend
        run: cd backend && npm run build

  security-audit:
    runs-on: ubuntu-latest
    name: Security Audit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Audit Frontend
        run: cd frontend && npm audit --audit-level=high

      - name: Audit Backend
        run: cd backend && npm audit --audit-level=high

  preview-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    name: Deploy Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Frontend dependencies
        run: cd frontend && npm ci

      - name: Deploy Preview to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          github-comment: true
